-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:BOE NS140WUM-L61",
  mode = "1920x1200@60",
  position = "6016x831",
  scale = 1.25,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL C2422HE 5W1XYG3",
  mode = "1920x1080@60",
  position = "1536x0",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:KOGAN AUSTRALIA PTY LTD KAMN32RT1SA 0000000000000",
  mode = "2560x1440@100",
  position = "3456x-250",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.config({
  cursor = { default_monitor = "desc:KOGAN AUSTRALIA PTY LTD KAMN32RT1SA 0000000000000" },
})
