[theme]
mode = "dark"
source = "builtin"
builtin = "Nord"

[wallpaper]
directory = "~/.config/wallpapers"

[shell]
time_format = "{:%R}" # 24-hour time
polkit_agent = true

[shell.animation]
enabled = false

[shell.greeter_sync]
auto_sync = true

[idle]
pre_action_fade_seconds = 0

[idle.behavior.display-off]
timeout = 600
action = "screen_off"
enabled = true

[idle.behavior.suspend-on-battery]
timeout = 1200
action = "command"
command = "if busctl --system get-property org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower OnBattery | grep -q 'b true'; then noctalia msg session lock-and-suspend; fi"
enabled = true

[hooks]
battery_charging = "noctalia msg config-reload"
battery_discharging = "noctalia msg config-reload"
battery_plugged = "noctalia msg config-reload"

[lockscreen]
fingerprint = true

[location]
address = "Canberra, Australia"
