[idle]
pre_action_fade_seconds = 2.0

[lockscreen]
lock_before_suspend = true

[hooks]
started             = "~/.config/noctalia/scripts/update-idle-profile.sh"
battery_charging    = "~/.config/noctalia/scripts/update-idle-profile.sh"
battery_plugged     = "~/.config/noctalia/scripts/update-idle-profile.sh"
battery_discharging = "~/.config/noctalia/scripts/update-idle-profile.sh"
